version: '2.1'
services:

  ####################################
  ####    SPRING CLOUD CONFIG     ####
  ####################################

  config:
    build: config-service
    image: johnnymerayo/config-service
    ports:
      - 8888:8888
    restart: always
    container_name: config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  ####################################
  ####  END SPRING CLOUD CONFIG   ####
  ####################################



  ####################################
  ####    SPRING ADMIN SERVICE    ####
  ####################################

  boot-admin:
    build: boot-admin
    image: johnnymerayo/boot-admin
    ports:
      - 8765:8765
    restart: always
    container_name: boot-admin
    environment:
      config_host: config
      SPRING_PROFILES_ACTIVE: docker
#      eureka_host: eureka-service
    depends_on:
      eureka-service:
        condition: service_healthy
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  ####################################
  ####  END SPRING ADMIN SERVICE  ####
  ####################################
  

  ####################################
  ####       NETFLIX OSS          ####
  ####################################
 
  #** EUREKA **#
  eureka-service:
    build: eureka-service
    image: johnnymerayo/eureka-service
    restart: always
    container_name: eureka-service
    environment:
      config_host: config
      SPRING_PROFILES_ACTIVE: docker
#      - eureka_host=eureka-service
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  #** HYSTRIX **#
  hystrix-dashboard:
    build: hystrix-dashboard
    image: johnnymerayo/hystrix-dashboard
    restart: always
    container_name: hystrix-dashboard
    environment:
      config_host: config
      SPRING_PROFILES_ACTIVE: docker
#      eureka_host: eureka-service
    depends_on:
      eureka-service:
        condition: service_healthy
      config:
        condition: service_healthy
    ports:
      - 8010:8010
    logging:
      options:
        max-size: "10m"
        max-file: "10"
              
  #** ZIPKIN **#
  zipkin-service:
    build: zipkin-service
    image: johnnymerayo/zipkin-service
    restart: always
    container_name: zipkin-service
    environment:
      config_host: config
      SPRING_PROFILES_ACTIVE: docker
#      eureka_host: eureka-service
    depends_on:
      eureka-service:
        condition: service_healthy
      config:
        condition: service_healthy
    ports:
      - 9411:9411
    logging:
      options:
        max-size: "10m"
        max-file: "10"
      
  ####################################
  ####      END NETFLIX OSS       ####
  ####################################
  
  
  client:
    build: client
    image: johnnymerayo/client
    restart: always
    container_name: client
    environment:
      config_host: config
      SPRING_PROFILES_ACTIVE: docker
#      eureka_host: eureka-service
    depends_on:
      config:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    ports:
      - 9999:9999
    logging:
      options:
        max-size: "10m"
        max-file: "10"
      
      
  ####################################
  ####    NOTIFICATION SERVICE    ####
  ####################################
   
  notification-service:
    build: notification-service
    image: johnnymerayo/notification-service
    ports:
      - 8080:8080
    restart: always
    container_name: notification-service
    environment:
      config_host: config
      SPRING_PROFILES_ACTIVE: docker
#      eureka_host: eureka-service
#      notification_db_host: db_notification
    depends_on:
      config:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
        
    volumes:
      - ./docker-data/logs/notification-service:/var/log/notification-service
      
    logging:
      options:
        max-size: "10m"
        max-file: "10"  
   
  db_notification:
    image: mysql:5.7.18
    container_name: notification_db
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: p45w0rd
      MYSQL_DATABASE: notification
      MYSQL_USER: ksims_db
      MYSQL_PASSWORD: p45w0rd
      
  ####################################
  ####  END  NOTIFICATION SERVICE ####
  ####################################
   

 
  ####################################
  ####        MAIL SERCICE        ####
  ####################################

  mail-service:
    build: mail-service
    image: johnnymerayo/mail-service
    ports:
      - 8081:8081
    restart: always
    container_name: mail-service
    environment:
      config_host: config
      SPRING_PROFILES_ACTIVE: docker
#      eureka_host: eureka-service
#      mail_db_host: db_mail
    depends_on:
      config:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
        
    volumes:
      - ./docker-data/logs/mail-service:/var/log/mail-service

    logging:
      options:
        max-size: "10m"
        max-file: "10"


  db_mail:
    image: mysql:5.7.18
    container_name: mail_db
    volumes:
      - ./docker-data/mysql_mail-service:/var/lib/mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: p45w0rd
      MYSQL_DATABASE: mail
      MYSQL_USER: ksims_db
      MYSQL_PASSWORD: p45w0rd

  ####################################
  ####    END  MAIL SERCICE       ####
  ####################################


  ####################################
  ####            VOLUMES         ####
  ####################################
#  notification_db_data: 
#    external:
#      name: docker-data




  ####################################
  ####         NETWORKS           ####
  ####################################

#networks:
#  xxxxx:
#    driver: bridge



